apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: conveyor-pipeline
  labels:
    app: loki
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3100
    targetPort: 3100
    protocol: TCP
  - name: grpc
    port: 9096
    targetPort: 9096
    protocol: TCP
  selector:
    app: loki
