apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: conveyor-pipeline
  labels:
    app: kafka
    component: messaging
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    name: kafka
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: conveyor-pipeline
  labels:
    app: kafka
    component: messaging
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 9092
    targetPort: 9092
    name: kafka
  selector:
    app: kafka