---
# ServiceAccount for Prometheus
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: conveyor-pipeline
  labels:
    app: prometheus
    component: monitoring

---
# ClusterRole: Read-only access for Kubernetes service discovery
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-reader
  labels:
    app: prometheus
    component: monitoring
rules:
  # Access to discover pods, services, and endpoints
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]

  # Access to read config maps (for service discovery)
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]

  # Access to read non-resource URLs (metrics endpoints)
  - nonResourceURLs:
      - /metrics
    verbs: ["get"]

---
# ClusterRoleBinding: Bind prometheus-sa to prometheus-reader role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-reader-binding
  labels:
    app: prometheus
    component: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-reader
subjects:
  - kind: ServiceAccount
    name: prometheus-sa
    namespace: conveyor-pipeline
