apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: conveyor-pipeline
  labels:
    app: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: conveyor-pipeline-sa
      containers:
      - name: processor
        image: j14le/conveyor-processor:ca3-metrics-tls
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: processor-config
        env:
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: admin-token
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
